import './globals.css';
import type {Metadata, Viewport} from 'next';
import {ReactQueryProviders} from '@/app/providers';
import {pretendard} from '@/shared/util/font';
import {BridgeProvider} from '@wraffle/bridge/src/web';
import {Toaster} from '@wraffle/ui';
import IconLoader from '@wraffle/ui/src/ui/icon/IconLoader';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const viewport: Viewport = {
  userScalable: false,
  initialScale: 1.0,
  maximumScale: 1,
  width: 'device-width',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${pretendard.variable} font-pretendard`}>
        <div className='container h-screen min-h-screen'>
          <ReactQueryProviders>
            <BridgeProvider>
              <Toaster />
              {IconLoader}
              {children}
            </BridgeProvider>
          </ReactQueryProviders>
        </div>
      </body>
    </html>
  );
}
